source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RSLiveStreaming' do

pod 'AFNetworking','~> 4.0'
pod 'SDWebImage','~> 5.0'
pod 'TXLiteAVSDK_Professional', :podspec => 'http://pod-1252463788.cosgz.myqcloud.com/liteavsdkspec/TXLiteAVSDK_Professional.podspec'
pod 'TXIMSDK_iOS'
pod 'Toast-Swift'
end
